Repository TherapEase-CEOS/TherapEase-FE, pull requests merged in 2023-07, with the labels that each got.

#19 feat : 상담일정표 컴포넌트 구현
  src/components/timetable/Profile.tsx
  src/components/timetable/TimeTable.tsx
  src/components/timetable/TimeTableCell.tsx
  src/components/timetable/TimeTableCol.tsx
  src/data/profile.json
  src/hooks/useInput.ts
  src/interface/interface.ts
  src/pages/timetable/index.tsx
  src/store/timetable.ts
  tailwind.config.js
Labels: ✨Feature, 🎨HTML&CSS

#17 feat: 감정조회 페이지 UI
  package-lock.json
  package.json
  src/assets/Emotion-log.png
  src/components/Buttons.tsx
  src/components/ClientCard.tsx
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/LeftBar.tsx
  src/components/records/LeftBar.tsx
  src/components/records/RecordGraph.tsx
  src/components/records/RecordsList.tsx
  src/components/records/SingleRecord.tsx
  src/constants/DUMMY_DATA.ts
  src/constants/records.ts
  src/interfaces/interfaces.ts
  src/pages/404.tsx
  src/pages/_error.tsx
  src/pages/records/index.tsx
  src/store/recoil.ts
  src/store/user.ts
  src/styles/globals.css
  src/utils/parseDate.ts
  tailwind.config.js
Labels: ✨Feature, 🎨HTML&CSS

#20 fix: AppleSDGothicNeo font file 변경
  public/fonts/AppleSDGothicNeoM.ttf
  public/fonts/AppleSDGothicNeoR.ttf
  src/components/Layout.tsx
  src/styles/globals.css
Labels: ⚙Setting

#22 feat: 내담자 관리 페이지 UI
  src/components/Alert.tsx
  src/components/ClientCard.tsx
  src/components/records/RecordsList.tsx
  src/pages/clients/index.tsx
  src/store/user.ts
Labels: ✨Feature, 🎨HTML&CSS

#25 feat: 감정기록세부 UI 개발-1
  next.config.js
  src/assets/Emotion-log.svg
  src/assets/log/negative-icon.svg
  src/assets/log/noidea-icon.svg
  src/assets/log/positive-icon.svg
  src/components/Buttons.tsx
  src/components/log/EmotionAddCard.tsx
  src/components/log/EmotionCard.tsx
  src/components/log/EmotionQuestionCard.tsx
  src/components/log/EmotionSelectCard.tsx
  src/constants/DUMMY_DATA.ts
  src/constants/EMOTION_QUESTIONS.tsx
  src/pages/log/index.tsx
  src/store/user.ts
  src/styles/globals.css
Labels: ✨Feature, 🎨HTML&CSS

#27 fix : 타임테이블 역할 구분
  src/interface/interface.ts
  src/pages/timetable/index.tsx
  src/store/timetable.ts
Labels: 🚨BugFix

#29 bugFix: 타임테이블 페이지 isEditMode default 값 수정
  src/pages/timetable/index.tsx
Labels: 🚨BugFix

#28 feat: 감정기록세부 UI 개발-2
  src/components/log/EmotionCard.tsx
  src/components/log/EmotionSelectCard.tsx
  src/components/log/OptionalInput.tsx
  src/components/records/RecordGraph.tsx
  src/components/records/SingleRecord.tsx
  src/interfaces/interfaces.ts
  src/pages/log/index.tsx
  src/pages/records/create.tsx
  src/pages/records/index.tsx
Labels: ✨Feature, 🎨HTML&CSS

#30 fix: SingleRecord 대분류감정 > 중분류감정 표시 수정 & 한글 label 적용
  src/components/ClientCard.tsx
  src/components/Header.tsx
  src/components/records/RecordGraph.tsx
  src/components/records/SingleRecord.tsx
  src/constants/DUMMY_DATA.ts
  src/store/recoil.ts
Labels: 🚨BugFix

#31 feat: 역할에 따른 코드인증 (로그인)
  package-lock.json
  package.json
  src/components/Header.tsx
  src/components/modals/InputModal.tsx
  src/components/modals/LoginModal.tsx
  src/constants/Config.tsx
  src/constants/constants.tsx
  src/constants/queryKeys.tsx
  src/hooks/queries/timetable.tsx
  src/hooks/queries/user.tsx
  src/hooks/useUser.tsx
  src/interfaces/interfaces.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/store/user.ts
  src/utils/HTTP.tsx
  src/utils/useClient.tsx
  tailwind.config.js
Labels: ✨Feature, 📬️API

#34 feat: 환경 별 API URL 분리
  .gitignore
  src/constants/Config.tsx
  src/utils/HTTP.tsx
Labels: ✨Feature, ⚙Setting

#37 fix: 감정세부기록 페이지 UI debugging
  src/components/log/EmotionSelectCard.tsx
  src/components/modals/ConfirmModal.tsx
  src/pages/clients/index.tsx
  src/pages/log/index.tsx
Labels: 🚨BugFix, ⛏Refactor

#36 fix: 내담자 관리 페이지 UI 코드리뷰 반영
  src/components/Alert.tsx
Labels: 🚨BugFix, ⛏Refactor
